# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-25 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171225_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('d', 'draft'), ('p', 'published'), ('w', 'withdrawn')], default='d', max_length=1),
            preserve_default=False,
        ),
    ]
