# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-26 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0003_auto_20171226_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_agent',
            field=models.CharField(default='Chrome', max_length=20),
            preserve_default=False,
        ),
    ]
